// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg8w66YP9H-4YnrdF41c8cGQqWHb81R24',
    appId: '1:890683591352:web:8fa098d61d4d5309fd824d',
    messagingSenderId: '890683591352',
    projectId: 'znar-academy-f91be',
    authDomain: 'znar-academy-f91be.firebaseapp.com',
    storageBucket: 'znar-academy-f91be.firebasestorage.app',
    measurementId: 'G-XEWCGZ0V9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUb8otORDQiGDcmKQIRy2GospnrfzWIg',
    appId: '1:890683591352:android:f47bf0e80241680bfd824d',
    messagingSenderId: '890683591352',
    projectId: 'znar-academy-f91be',
    storageBucket: 'znar-academy-f91be.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlLLvDf7ks_n4HgOp05ofBtksrMaGxSg0',
    appId: '1:890683591352:ios:85ed829e65ee1a67fd824d',
    messagingSenderId: '890683591352',
    projectId: 'znar-academy-f91be',
    storageBucket: 'znar-academy-f91be.firebasestorage.app',
    iosBundleId: 'com.example.znarAcademy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlLLvDf7ks_n4HgOp05ofBtksrMaGxSg0',
    appId: '1:890683591352:ios:85ed829e65ee1a67fd824d',
    messagingSenderId: '890683591352',
    projectId: 'znar-academy-f91be',
    storageBucket: 'znar-academy-f91be.firebasestorage.app',
    iosBundleId: 'com.example.znarAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg8w66YP9H-4YnrdF41c8cGQqWHb81R24',
    appId: '1:890683591352:web:21071fdb426979f9fd824d',
    messagingSenderId: '890683591352',
    projectId: 'znar-academy-f91be',
    authDomain: 'znar-academy-f91be.firebaseapp.com',
    storageBucket: 'znar-academy-f91be.firebasestorage.app',
    measurementId: 'G-WX5ZQ8CXD6',
  );
}
